/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.br.edu.ifnmg.tcd.screen;

import com.br.edu.ifnmg.tcd.credential.Credential;

/**
 *
 * @author Felkng <&it;felkng374 at @gmail.com&gt;>
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    private static TelaPrincipal instance;

    public TelaPrincipal() {
        initComponents();
    }

    public static TelaPrincipal getInstance(Credential credential) {

        if (instance == null) {
            instance = new TelaPrincipal();
        }

        //<editor-fold defaultstate="collapsed" desc="Ativação/Desativação de menus">
        // Escolha entre ocultar
        // Perceba que a própria classe pode ter acesso direto a seus atributos
        // privados. Por isso não houve um ...getMnuCadastroUsuario()
//        instance.mnuEmprestimo.setVisible(credencial.getUser().getRole().getName().equals("bibliotecario"));
//        instance.mnuBook.setVisible(credencial.getUser().getRole().getName().equals("bibliotecario"));
        instance.mnuAddBook.setVisible(credential.getUser().getRole().getName().equals("bibliotecario"));
        instance.mnuAddEmp.setVisible(credential.getUser().getRole().getName().equals("bibliotecario"));
        instance.setTitle("Tela Principal - " + credential.getUser().getName());

        // ... ou desabilitar
//        instance.mnuCadastroUsuario.setEnabled(credencial.isAdministrador());
        //</editor-fold>
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        mnuUser = new javax.swing.JMenu();
        mnuQueryUsr = new javax.swing.JMenuItem();
        mnuUpdateUsr = new javax.swing.JMenuItem();
        mnuBook = new javax.swing.JMenu();
        mnuQueryBook = new javax.swing.JMenuItem();
        mnuAddBook = new javax.swing.JMenuItem();
        mnuEmprestimo = new javax.swing.JMenu();
        mnuQueryEmp = new javax.swing.JMenuItem();
        mnuAddEmp = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(64, 64, 64));
        setPreferredSize(new java.awt.Dimension(665, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(64, 64, 64));
        jPanel1.setForeground(new java.awt.Color(64, 64, 64));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        menuBar.setBackground(new java.awt.Color(40, 40, 40));
        menuBar.setBorder(null);
        menuBar.setForeground(new java.awt.Color(0, 0, 0));
        menuBar.setBorderPainted(false);

        mnuUser.setBackground(new java.awt.Color(70, 70, 70));
        mnuUser.setForeground(new java.awt.Color(0, 0, 0));
        mnuUser.setText("Usuário");

        mnuQueryUsr.setText("Ver Usuário");
        mnuUser.add(mnuQueryUsr);

        mnuUpdateUsr.setText("alterar Usuário");
        mnuUser.add(mnuUpdateUsr);

        menuBar.add(mnuUser);

        mnuBook.setBackground(new java.awt.Color(70, 70, 70));
        mnuBook.setForeground(new java.awt.Color(0, 0, 0));
        mnuBook.setText("Livro");

        mnuQueryBook.setText("Ver Livos");
        mnuBook.add(mnuQueryBook);

        mnuAddBook.setText("Cadastrar Livro");
        mnuBook.add(mnuAddBook);

        menuBar.add(mnuBook);

        mnuEmprestimo.setText("Empréstimo");

        mnuQueryEmp.setText("Ver Empréstimo");
        mnuEmprestimo.add(mnuQueryEmp);

        mnuAddEmp.setText("Cadastrar Empréstimo");
        mnuEmprestimo.add(mnuAddEmp);

        menuBar.add(mnuEmprestimo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        TelaLogin.getInstance().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAddBook;
    private javax.swing.JMenuItem mnuAddEmp;
    private javax.swing.JMenu mnuBook;
    private javax.swing.JMenu mnuEmprestimo;
    private javax.swing.JMenuItem mnuQueryBook;
    private javax.swing.JMenuItem mnuQueryEmp;
    private javax.swing.JMenuItem mnuQueryUsr;
    private javax.swing.JMenuItem mnuUpdateUsr;
    private javax.swing.JMenu mnuUser;
    // End of variables declaration//GEN-END:variables
}
