/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.br.edu.ifnmg.tcd.screen;

import com.br.edu.ifnmg.tcd.credential.Credential;
import com.br.edu.ifnmg.tcd.credential.CredentialDao;
import com.br.edu.ifnmg.tcd.user.User;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Felkng <&it;felkng374 at @gmail.com&gt;>
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    private static TelaLogin instance;

    private TelaLogin() {
        initComponents();
    }

    public static TelaLogin getInstance() {
        if (instance == null) {
            instance = new TelaLogin();
        }

        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        lblUsr = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        pwdSenha = new javax.swing.JPasswordField();
        btnConfirma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/png-transparent-user-profile-computer-icons-login-user-avatars-thumbnail.png")));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(60, 60, 60));

        txtUser.setBackground(new java.awt.Color(64, 64, 64));
        txtUser.setForeground(new java.awt.Color(255, 255, 255));

        lblUsr.setBackground(new java.awt.Color(64, 64, 64));
        lblUsr.setForeground(new java.awt.Color(255, 255, 255));
        lblUsr.setText("Usuário:");

        lblPwd.setBackground(new java.awt.Color(64, 64, 64));
        lblPwd.setForeground(new java.awt.Color(255, 255, 255));
        lblPwd.setText("Senha:");

        pwdSenha.setBackground(new java.awt.Color(64, 64, 64));
        pwdSenha.setForeground(new java.awt.Color(255, 255, 255));

        btnConfirma.setBackground(new java.awt.Color(64, 64, 64));
        btnConfirma.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirma.setText("Confirmar");
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUsr)
                        .addGap(18, 18, 18)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirma)
                            .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsr))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd)
                    .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
        User usuario = null;
        Credential c = null;
        try {
            c = new Credential();
            c.setUsername(txtUser.getText());
            c.setPassword(new String(pwdSenha.getPassword()));
            usuario = new CredentialDao().authenticate(c);
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
//        System.out.println(usuario);

        if (usuario != null) {

            // Usuário autenticado
            System.out.println("Usuário e senha corretos");

            //  Oculta esta janela
            this.setVisible(false);

            // Prepara campos para nova entrada
            pwdSenha.setText(null);
            txtUser.requestFocus();
            txtUser.selectAll();

            // Adoção do Singleton impede acesso direto ao construtor
//            new TelaPrincipal().setVisible(true);
            // TelaPrincipal requer a Credencial para habilitar/desabilitar menus
//            TelaPrincipal.getInstance().setVisible(true);
            TelaPrincipal.getInstance(usuario.getCredential()).setVisible(true);

        } else {

            // Usuário NÃO-autenticado
            System.out.println("Usuáiro e senha INCORRETOS");
            txtUser.requestFocus();
            txtUser.selectAll();
            pwdSenha.setText(null);
            // Apenas como exemplo!
            // Para melhorar a usabilidade do sistema, exibir um rótulo contendo
            // a mensagem é preferível em vez de uma mensagem que requer que
            // o usuário interaja com ela
            JOptionPane.showMessageDialog(this, "Usuário e/ou senha inválidos.\nTente novamente.");
        }

    }//GEN-LAST:event_btnConfirmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaLogin.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblUsr;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
