/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.br.edu.ifnmg.tcd.screen;

import com.br.edu.ifnmg.tcd.credential.Credential;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatCarbonIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatCobalt2IJTheme;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatDarkPurpleIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatDraculaIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoDeepOceanIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoMidnightBlueIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatGruvboxDarkHardIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatHiberbeeDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatMonocaiIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatMonokaiProIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatNordIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatOneDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatSolarizedDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatSpacegrayIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatVuesionIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatXcodeDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkIJTheme;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.UIManager;

/**
 *
 * @author Felkng <&it;felkng374 at @gmail.com&gt;>
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    private static TelaPrincipal instance;

    public TelaPrincipal() {
        initComponents();
    }

    public static TelaPrincipal getInstance(Credential credential) {

        if (instance == null) {
            instance = new TelaPrincipal();
        }

        //<editor-fold defaultstate="collapsed" desc="Ativação/Desativação de menus">
        // Escolha entre ocultar
        // Perceba que a própria classe pode ter acesso direto a seus atributos
        // privados. Por isso não houve um ...getMnuCadastroUsuario()
        instance.mnuNewUser.setVisible(credential.getUser().getRole().getName().equals("ADMINISTRADOR"));
        instance.mnuAddBook.setVisible(!credential.getUser().getRole().getName().equals("LEITOR"));
        instance.mnuAddEmp.setVisible(!credential.getUser().getRole().getName().equals("LEITOR"));
        instance.setTitle("Tela Principal - " + credential.getUser().getName());

        // ... ou desabilitar
//        instance.mnuCadastroUsuario.setEnabled(credencial.isAdministrador());
        //</editor-fold>
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        mnuUser = new javax.swing.JMenu();
        mnuQueryUsr = new javax.swing.JMenuItem();
        mnuUpdateUsr = new javax.swing.JMenuItem();
        mnuNewUser = new javax.swing.JMenuItem();
        jmnuOut = new javax.swing.JMenuItem();
        mnuBook = new javax.swing.JMenu();
        mnuQueryBook = new javax.swing.JMenuItem();
        mnuAddBook = new javax.swing.JMenuItem();
        mnuEmprestimo = new javax.swing.JMenu();
        mnuQueryEmp = new javax.swing.JMenuItem();
        mnuAddEmp = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(64, 64, 64));
        setPreferredSize(new java.awt.Dimension(665, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        menuBar.setBorder(null);
        menuBar.setBorderPainted(false);

        mnuUser.setText("Usuário");

        mnuQueryUsr.setText("Ver Usuário");
        mnuUser.add(mnuQueryUsr);

        mnuUpdateUsr.setText("Alterar Usuário");
        mnuUser.add(mnuUpdateUsr);

        mnuNewUser.setText("Cadastrar Novo Usuário");
        mnuUser.add(mnuNewUser);

        jmnuOut.setText("Sair");
        jmnuOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuOutActionPerformed(evt);
            }
        });
        mnuUser.add(jmnuOut);

        menuBar.add(mnuUser);

        mnuBook.setText("Livro");

        mnuQueryBook.setText("Ver Livos");
        mnuBook.add(mnuQueryBook);

        mnuAddBook.setText("Cadastrar Livro");
        mnuBook.add(mnuAddBook);

        menuBar.add(mnuBook);

        mnuEmprestimo.setText("Empréstimo");

        mnuQueryEmp.setText("Ver Empréstimo");
        mnuEmprestimo.add(mnuQueryEmp);

        mnuAddEmp.setText("Cadastrar Empréstimo");
        mnuEmprestimo.add(mnuAddEmp);

        menuBar.add(mnuEmprestimo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        TelaLogin.getInstance().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jmnuOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuOutActionPerformed
        this.setVisible(false);
        TelaLogin.getInstance().setVisible(true);
    }//GEN-LAST:event_jmnuOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            if (LocalDateTime.now().getHour() > 18 && LocalDateTime.now().getHour() < 6) {
                FlatDarkPurpleIJTheme.setup(); //2
            } else {
                FlatMonokaiProIJTheme.setup(); //1
            }
        }//            FlatMonokaiProIJTheme.setup(); //1
        //            FlatDarkPurpleIJTheme.setup(); //2
        //            FlatOneDarkIJTheme.setup(); //3
        //            FlatAtomOneDarkIJTheme.setup(); //4
        //            FlatArcDarkOrangeIJTheme.setup(); //5
        catch (Exception e) {
            e.printStackTrace();
        }
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JMenuItem jmnuOut;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAddBook;
    private javax.swing.JMenuItem mnuAddEmp;
    private javax.swing.JMenu mnuBook;
    private javax.swing.JMenu mnuEmprestimo;
    private javax.swing.JMenuItem mnuNewUser;
    private javax.swing.JMenuItem mnuQueryBook;
    private javax.swing.JMenuItem mnuQueryEmp;
    private javax.swing.JMenuItem mnuQueryUsr;
    private javax.swing.JMenuItem mnuUpdateUsr;
    private javax.swing.JMenu mnuUser;
    // End of variables declaration//GEN-END:variables
}
